name = "pa-housing-fund"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "pa-housing-fund-db"
database_id = "2b23eef5-d4f6-493f-ab6c-7498a27d6eb9"
